(cond ((> emacs-major-version 23)       ; emacs 24 has `load-theme', see `customize-themes'
       (if (window-system)
           (load-theme 'tsdh-dark t)
         (load-theme 'tango t)))
       ;; (load-theme 'tango t))
       ;; (load-theme 'tsdh-light t))
       ;; (load-theme 'whiteboard t))
       ;; (load-theme 'adwaita t))
       ;; (load-theme 'deeper-blue t))
       ;; (load-theme 'dichromacy t))
       ;; (load-theme 'light-blue t))
       ;; (load-theme 'manoj-dark t))
       ;; (load-theme 'misterioso t))
       ;; (load-theme 'tango t))
       ;; (load-theme 'tango-dark t))
       ;; (load-theme 'tsdh-dark t))
       ;; (load-theme 'tsdh-light t))
       ;; (load-theme 'wheatgrass t))
       ;; (load-theme 'whiteboard t))
       ;; (load-theme 'wombat t))
      (t
       (require 'color-theme)
       (when (featurep 'color-theme)    ; otherwise, use `color-theme'
         (color-theme-initialize)
         (color-theme-montz))))
