(color-theme-initialize)

;; color theme based on `color-theme-montz'
(color-theme-montz)

;; (eval-when-compile    (require 'color-theme))
;; (defun my-color-theme ()
;;   "Color theme by solgo, created 2014-02-10."
;;   (interactive)
;;   (color-theme-install
;;    '(my-color-theme
;;      ((background-color . "unspecified-bg")
;;       (background-mode . light)
;;       (foreground-color . "unspecified-fg"))
;;      ((cscope-use-face . t)
;;       (ibuffer-deletion-face . font-lock-type-face)
;;       (ibuffer-filter-group-name-face . bold)
;;       (ibuffer-marked-face . font-lock-warning-face)
;;       (ibuffer-title-face . font-lock-type-face)
;;       (list-matching-lines-buffer-name-face . underline)
;;       (list-matching-lines-face . match)
;;       (view-highlight-face . highlight)
;;       (widget-mouse-face . highlight))
;;      (default ((t (:stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
;;      (bold ((t (:bold t :weight bold))))
;;      (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
;;      (border ((t (nil))))
;;      (buffer-menu-buffer ((t (:bold t :weight bold))))
;;      (button ((t (:underline t))))
;;      (c-nonbreakable-space-face ((t (:background "red"))))
;;      (comint-highlight-input ((t (:bold t :weight bold))))
;;      (comint-highlight-prompt ((t (:foreground "dark blue"))))
;;      (completions-annotations ((t (:underline t))))
;;      (completions-common-part ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :height 1))))
;;      (completions-first-difference ((t (:bold t :weight bold))))
;;      (cscope-file-face ((t (:foreground "blue"))))
;;      (cscope-function-face ((t (:foreground "magenta"))))
;;      (cscope-line-face ((t (:foreground "black"))))
;;      (cscope-line-number-face ((t (:foreground "red"))))
;;      (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
;;      (cursor ((t (nil))))
;;      (dired-directory ((t (:bold t :weight bold :foreground "blue"))))
;;      (dired-flagged ((t (:foreground "red"))))
;;      (dired-header ((t (:foreground "green"))))
;;      (dired-ignored ((t (:foreground "green"))))
;;      (dired-mark ((t (:foreground "magenta"))))
;;      (dired-marked ((t (:foreground "red"))))
;;      (dired-perm-write ((t (:foreground "red"))))
;;      (dired-symlink ((t (:bold t :weight bold :foreground "cyan"))))
;;      (dired-warning ((t (:foreground "red"))))
;;      (eim-string-face ((t (:underline t))))
;;      (eim-tooltip-face ((t (:foreground "black" :background "lightyellow" :family "Sans Serif"))))
;;      (escape-glyph ((t (:foreground "brown"))))
;;      (file-name-shadow ((t (:foreground "green"))))
;;      (fixed-pitch ((t (:family "Monospace"))))
;;      (font-lock-builtin-face ((t (:bold t :foreground "blue" :weight bold))))
;;      (font-lock-comment-delimiter-face ((t (:foreground "red"))))
;;      ;; (font-lock-comment-face ((t (:foreground "red"))))
;;      (font-lock-comment-face ((t (:foreground "#e5e5e5"))))
;;      (font-lock-constant-face ((t (:foreground "magenta"))))
;;      (font-lock-doc-face ((t (:foreground "green"))))
;;      (font-lock-function-name-face ((t (:bold t :foreground "blue" :weight bold))))
;;      (font-lock-keyword-face ((t (:bold t :foreground "cyan" :weight bold))))
;;      (font-lock-negation-char-face ((t (nil))))
;;      (font-lock-preprocessor-face ((t (:bold t :weight bold :foreground "blue"))))
;;      (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
;;      (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
;;      (font-lock-string-face ((t (:foreground "green"))))
;;      (font-lock-type-face ((t (:foreground "green"))))
;;      (font-lock-variable-name-face ((t (:foreground "yellow" :weight light))))
;;      ;; (font-lock-warning-face ((t (:foreground "red"))))
;;      (font-lock-warning-face ((t (:foreground "magenta"))))
;;      (fringe ((t (:background "grey95"))))
;;      (header-line ((t (:underline t))))
;;      (help-argument-name ((t (nil))))
;;      (highlight ((t (:background "green" :foreground "black"))))
;;      (ido-first-match ((t (:bold t :weight bold))))
;;      (ido-incomplete-regexp ((t (:foreground "red"))))
;;      (ido-indicator ((t (:background "red" :foreground "yellow" :width condensed))))
;;      (ido-only-match ((t (:foreground "ForestGreen"))))
;;      (ido-subdir ((t (:foreground "red"))))
;;      (isearch ((t (:background "magenta4" :foreground "cyan1"))))
;;      (isearch-fail ((t (:background "red"))))
;;      (italic ((t (:underline t))))
;;      (lazy-highlight ((t (:background "turquoise3"))))
;;      (link ((t (:foreground "blue" :underline t))))
;;      (link-visited ((t (:underline t :foreground "magenta4"))))
;;      (match ((t (:background "yellow" :foreground "black"))))
;;      (menu ((t (nil))))
;;      (minibuffer-prompt ((t (:foreground "medium blue"))))
;;      (mode-line ((t (nil))))
;;      (mode-line-buffer-id ((t (:bold t :weight bold))))
;;      (mode-line-emphasis ((t (:bold t :weight bold))))
;;      (mode-line-highlight ((t (:foreground "black" :background "green"))))
;;      (mode-line-inactive ((t (nil))))
;;      (mouse ((t (nil))))
;;      (next-error ((t (:foreground "white" :background "blue"))))
;;      (nobreak-space ((t (:background "magenta"))))
;;      (pp^L-highlight ((t (nil))))
;;      (query-replace ((t (:foreground "cyan1" :background "magenta4"))))
;;      (region ((t (:background "blue" :foreground "white"))))
;;      (scroll-bar ((t (nil))))
;;      (secondary-selection ((t (:background "cyan" :foreground "black"))))
;;      (shadow ((t (:foreground "green"))))
;;      (show-paren-match ((t (:background "turquoise"))))
;;      (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
;;      (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
;;      (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
;;      (trailing-whitespace ((t (:background "red1"))))
;;      (underline ((t (:underline t))))
;;      (variable-pitch ((t (:family "Sans Serif"))))
;;      (vertical-border ((t (nil))))
;;      (widget-button ((t (:bold t :weight bold))))
;;      (widget-button-pressed ((t (:foreground "red"))))
;;      (widget-documentation ((t (:foreground "dark green"))))
;;      (widget-field ((t (:background "yellow3" :foreground "black"))))
;;      (widget-inactive ((t (:foreground "green"))))
;;      (widget-single-line-field ((t (:background "green3" :foreground "black")))))))
;; (add-to-list 'color-themes '(my-color-theme  "Based on montz" "enroute.smth@gmail.com"))

;; (my-color-theme)

(provide '06color)